auditores_suscerte/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout as deslogeo
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (password_reset,
        password_reset_done, password_reset_confirm,
        password_reset_complete, password_change,
        password_change_done)
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from personas.views import PersonalesView
from curriculum.views import (PerfilView,
    EducacionView, LaboralView, CompetenciaView,
    HabilidadView, ConocimientoView, IdiomaView,
    CitasView, CertificacionView, CursoView,
    VerAuditores, EvaluacionView, revisar_acreditaciones,
    AcreditarView, FijarCitaView, DatosView)
from authentication.views import *
from authentication.forms import (ValidatingSetPasswordForm,
    ValidatingPasswordChangeForm)
from django.contrib.auth.decorators import login_required
import os


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^clave/reestablecer/?$',
        password_reset,
        {'post_reset_redirect': reverse_lazy('password_reset_done'),
         'template_name': 'auth/password_reset_form.html',
         'email_template_name': 'auth/reset_subject.html'},
        name='password_reset'),

    url(r'^clave/solicitud_envio/?$',
        password_reset_done,
        {'template_name': 'auth/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^clave_cambiada/$',
        password_change_done,
        {'template_name': 'auth/clave_cambiada.html'},
        name='password_change_done'),

    url(r'^clave/confirmacion/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete'),
         'template_name': 'auth/confirmar_cambiar_clave.html',
         'set_password_form': ValidatingSetPasswordForm},
        name='password_reset_confirm'),

    url(r'^clave/reestablcimiento/completo/$',
        password_reset_complete,
        {'template_name': 'auth/clave_cambiada.html'},
        name='password_reset_complete'),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^personas/',
        include('personas.urls')),

    url(r'^curriculum/',
        include('curriculum.urls')),

    url(r'logout/',
        deslogeo,
        {'next_page': '/'},
        name='salir'),

    url(r'login/',
        auth,
        name='auth'),

    url(r'cambiar_clave/',
        login_required(password_change),
        {'password_change_form': ValidatingPasswordChangeForm,
        'template_name': 'auth/password_reset_form.html',
        'post_change_redirect': 'logout/',
        'extra_context':
            {'cambiar_clave': True,
             'formulario': True,
             'titulo': u'cambiar contraseña',
             'palabra_clave': 'cambiar'},
        },
        name='cambiar_clave'),

    url(r'^listado_auditores/',
        VerAuditores.as_view(),
        name='listado_auditores'),

    url(r'^perfil/citas/$',
        login_required(CitasView.as_view()),
        name='citas'),

    url(r'^perfil/educacion/(?P<palabra>\w+)/(?P<educacion_id>[\d]+)*$',
        login_required(EducacionView.as_view()),
        name='educacion'),

    url(r'^perfil/laboral/(?P<palabra>\w+)/(?P<laboral_id>[\d]+)*$',
        login_required(LaboralView.as_view()),
        name='laboral'),

    url(r'^perfil/conocimiento/(?P<palabra>\w+)/(?P<conocimiento_id>[\d]+)*$',
        login_required(ConocimientoView.as_view()),
        name='conocimiento'),

    url(r'^perfil/evaluacion/(?P<evaluacion_id>[\d]+)/(?P<aspirante_id>[\d]+)/',
        login_required(EvaluacionView.as_view()),
        name='evaluacion'),

    url(r'^perfil/competencia/(?P<aspirante_id>[\d]+)/',
        login_required(CompetenciaView.as_view()),
        name='competencia'),

    url(r'^perfil/habilidad/(?P<palabra>\w+)/(?P<habilidad_id>[\d]+)*$',
        login_required(HabilidadView.as_view()),
        name='habilidad'),

    url(r'^perfil/idioma/(?P<palabra>\w+)/(?P<idioma_id>[\d]+)*$',
        login_required(IdiomaView.as_view()),
        name='idioma'),

    url(r'^perfil/curso/(?P<palabra>\w+)/(?P<curso_id>[\d]+)*$',
        login_required(CursoView.as_view()),
        name='curso'),

    url(r'^perfil/certificacion/(?P<palabra>\w+)/(?P<certificacion_id>[\d]+)*$',
        login_required(CertificacionView.as_view()),
        name='certificacion'),

    url(r'^perfil/$',
        login_required(PerfilView.as_view()),
        name='perfil'),

    url(r'^revisar_acreditaciones/$',
        'curriculum.views.revisar_acreditaciones',
        name='revisar_acreditaciones'),

    url(r'^revisar_datos/(?P<usuario_id>[\d]+)/',
        login_required(DatosView.as_view()),
        name='requisitos'),

    url(r'^acreditar/(?P<usuario_id>[\d]+)*$',
        login_required(AcreditarView.as_view()),
        name='acreditar'),

    url(r'^fijar_cita/(?P<usuario_id>[\d]+)*$',
        login_required(FijarCitaView.as_view()),
        name='acreditar'),

    url(r'^$',
        auth, name='inicio'),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': os.path.join(os.path.dirname(__file__), 'static')}),
    )

personas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from views import (CrearPersonaView, EditarPersonaView)

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^crear/',
        login_required(CrearPersonaView.as_view()),
        name='crear_persona'),

    url(r'^editar/*$',
        login_required(EditarPersonaView.as_view()),
        name='editar_persona'),

)

personas/models.py
# -*- coding: UTF8 -*-
from django.db import models
from django.core.validators import MaxLengthValidator
from lugares.models import *

# Modelo de Persona
ESTADO_CIVIL = (('s', 'Soltero(a)'),
                ('c', 'Casado(a)'),
                ('d', 'Divorciado(a)'),
                ('v', 'Viudo(a)'))

TELEFONO_PUBLICO = (('movil', u'Teléfono móvil'),
                    ('fijo', u'Teléfono de residencia'),
                    ('oficina', u'Teléfono de oficina'),
                    )


class Estatus(models.Model):
    '''
    Modelo de registro para distintos estados
    con sus diferentes dependencias
    '''
    nombre = models.CharField(max_length=50)
    dependencia = models.ForeignKey("self", null=True, blank=True)
    class Meta:
        db_table = u'estatus'
        verbose_name_plural = "estatus"

    def __unicode__(self):
        return u'%s' % (self.nombre)


class Persona(models.Model):
    '''
    Tabla de registro de personas
    '''
    cedula = models.CharField(
            max_length=50,
            unique=True,
            verbose_name=u'Cédula',
            help_text=u'Los datos deben ser únicamente números')
    primer_nombre = models.CharField(
            max_length=50,
            help_text='Indique su primer nombre')
    segundo_nombre = models.CharField(
            max_length=50,
            blank=True,
            help_text='Indique su segundo nombre, si posee')
    primer_apellido = models.CharField(
            max_length=50,
            help_text='Indique su primer apellido')
    segundo_apellido = models.CharField(
            max_length=50,
            blank=True,
            help_text='Indique su segundo apellido')
    genero = models.IntegerField(choices=((0, 'Masculino'),
                (1, 'Femenino')),
            default=0,
            verbose_name=u'género',
            help_text='Seleccione su género')
    reside = models.ForeignKey(Estado,
            help_text=u'Estado de residencia')
    direccion = models.TextField(
            verbose_name=u'dirección',
            blank=True,
            help_text=u'Indique dirección donde reside')
    fecha_nacimiento = models.DateField(
            blank=True,
            null=True,
            help_text='Indique su fecha de nacimiento')
    tlf_reside = models.CharField(
            max_length=15,
            verbose_name=u'teléfono de residencia',
            help_text=u'Número telefónico de residencia')
    tlf_movil = models.CharField(
            max_length=15,
            blank=True,
            verbose_name=u'teléfono móvil',
            help_text=u'Número telefónico celular')
    tlf_oficina = models.CharField(
            max_length=15,
            blank=True,
            verbose_name=u'teléfono de oficina',
            help_text=u'Número telefónico de oficina')
    tlf_contacto = models.CharField(
            choices=TELEFONO_PUBLICO,
            max_length=10,
            help_text=u'Seleccione el teléfono que establecerá \
                    el cual será contactado',
            default='fijo',
            verbose_name=u'teléfono de contacto (tome en cuenta que \
                    esta información será pública)')
    estado_civil = models.CharField(
            choices=ESTADO_CIVIL,
            max_length=15,
            blank=True,
            help_text='Señale su estado civil',
            default='s')
    email = models.EmailField(
            help_text='Indique un correo electrónico válido',
            unique=True,
            verbose_name=u'Email (tome en cuenta que \
                    esta información será pública)',
            validators=[MaxLengthValidator(2000)])

    class Meta:
        db_table = u'personas'
        verbose_name = "persona"

    def __unicode__(self):
        return u'%s %s %s' % (
                self.cedula,
                self.primer_apellido,
                self.primer_nombre)


class Auditor(models.Model):
    persona = models.ForeignKey('Persona')
    estatus = models.ForeignKey('Estatus')
    fecha = models.DateField()
    observacion = models.TextField(
            help_text='Razones por la cual se acredita o desacredita al auditor',
            verbose_name=u'observación')

    class Meta:
        db_table = u'auditor'
        verbose_name = 'auditor'
        verbose_name_plural = 'auditores'

    def __unicode__(self):
        return u'%s' % (self.persona)


class CertificadoElectronico(models.Model):
    from authentication.models import UserProfile
    usuario = models.ForeignKey(UserProfile)
    certificado = models.CharField(max_length=5000)

    class Meta:
        db_table = u'certificado_electonico'
        verbose_name = u'certificado electrónico'
        verbose_name_plural = u'certificados electrónicos'

    def __unicode__(self):
        return u'%s' % (self.usuario)

main/templates/perfil/datos_usuario.html
{% include "base_ink.html" %}

{% block personales %}

<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
  <body>

{% load static %}
{% load humanize %} 
{% load perfil %}
 
  <!-- Main Page Content and Sidebar -->
  
<div class="ink-grid">
    {% include 'menu_perfil.html' %}

    <div class="space">
        {% if mensaje %}
            <div class="ink-alert basic {{ tipo_mensaje }}">
                <button class="ink-dismiss" id="cerrar">&times;</button>
                <p>{{ mensaje }}</p>
            </div>
        {% endif %}
        <div class="column-group gutters">
            <div class="large-30 medium-100 small-100 push-left">
                {% include "perfil/informacion_personal.html" %}
            </div>
            <div class="large-70 medium-100 small-100 push-right">
                <div class="box">
                <h4><div class="ink-titulo_superior"><i class="icon-check-minus"></i> {{ usuario.get_profile.persona.primer_nombre }} {{ usuario.get_profile.persona.primer_apellido }}</div></h4>
                    <div class="ink-tabs top"> 
                        <ul class="tabs-nav">
                            <li><a href="#personales">Datos personales</a></li>
                            <li><a href="#curriculum">Resumen curricular</a></li>
                            <li><a href="#requisitos">Requisitos de auditor</a></li>
                        </ul>
                        <div id="personales" class="tabs-content"> 
                            <br />
                            <b>Cédula de identidad:</b> {{ usuario.get_profile.persona.cedula }}
                            <br />
                            <b>Primer nombre:</b> {{ usuario.get_profile.persona.primer_nombre }}
                            <br />
                            <b>Primer apellido:</b> {{ usuario.get_profile.persona.primer_apellido }}
                            <br />
                            <b>Segundo nombre:</b> {{ usuario.get_profile.persona.segundo_nombre }}
                            <br />
                            <b>Segundo apellido:</b> {{ usuario.get_profile.persona.segundo_apellido }}
                            <br />
                            <b>Género:</b> 
                                {% ifequal usuario.get_profile.persona.genero 0 %}
                                    Masculino
                                {% else %}
                                    Femenino
                                {% endifequal %}
                            <br />
                            <b>Reside:</b> {{ usuario.get_profile.persona.reside }}
                            <br />
                            <b>Dirección:</b> {{ usuario.get_profile.persona.direccion }}
                            <br />
                            <b>Fecha de nacimiento:</b> {{ usuario.get_profile.persona.fecha_nacimiento|date:"DATE_FORMAT" }}
                            <br />
                            <b>Teléfono de residencia:</b> {{ usuario.get_profile.persona.tlf_reside }}
                            <br />
                            <b>Fecha móvil:</b> {{ usuario.get_profile.persona.tlf_movil }}
                            <br />
                            <b>Fecha de oficina:</b> {{ usuario.get_profile.persona.tlf_oficina }}
                            <br />
                            <b>Estado civil:</b> 
                                {% ifequal usuario.get_profile.persona.estado_civil 's' %}
                                    Solter{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
                                {% endifequal %}
                                {% ifequal usuario.get_profile.persona.estado_civil 'c' %}
                                    Casad{% ifequal usuario.get_profile.persona.genero 0 %}o{% else %}a{% endifequal %}
                                {% endifequal %}
                                {% ifequal usuario.get_profile.persona.estado_civil 'd' %}
                                    Divorciad{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
                                {% endifequal %}
                                {% ifequal usuario.get_profile.persona.estado_civil 'v' %}
                                    Viud{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
                                {% endifequal %}
                            <br />
                            <b>Correo electrónico:</b> <a href="mailto:{{ usuario.get_profile.persona.email }}">{{ usuario.get_profile.persona.email }}</a>
                            <br />
                        </div>


                        <div id="curriculum" class="tabs-content"> 
                            <h4>Educación</h4>
                            <hr>
                            {% for educacion in usuario.get_profile.persona.educacion_set.get_queryset %}
                                <b>Título: </b> {{ educacion.titulo }}
                                <br />
                                <b>Institución: </b> {{ educacion.institucion }}
                                <br />
                                <b>Tipo: </b> {{ educacion.tipo }}
                                <br />
                                <b>Fecha de inicio: </b> {{ educacion.fecha_inicio|date:"DATE_FORMAT" }}
                                <br />
                                <b>Fecha culminación: </b> {{ educacion.fecha_fin|date:"DATE_FORMAT" }}
                                <br /><br >
                            {% endfor %}

                            <br />

                            <h4>Información laboral</h4>
                            <hr>
                            {% for laboral in usuario.get_profile.laboral_set.get_queryset %}
                                <b>Empresa: </b> {{ laboral.empresa }}
                                <br />
                                <b>Cargo: </b> {{ laboral.cargo }}
                                <br />
                                <b>Fecha de inicio: </b> {{ laboral.fecha_inicio|date:"DATE_FORMAT" }}
                                <br />
                                <b>Fecha de culminación: </b> {{ laboral.fecha_fin|date:"DATE_FORMAT" }}
                                <br />
                                <b>Función: </b> {{ laboral.funcion }}
                                <br />
                                <b>Estado: </b> {{ laboral.estado }}
                                <br /><br >
                            {% endfor %}

                            <br />

                            <h4>Cursos</h4>
                            <hr>
                            {% for curso in usuario.get_profile.curso_set.get_queryset %}
                                <b>Titulo: </b> {{ curso.titulo }}
                                <br />
                                <b>Institución: </b> {{ curso.institucion }}
                                <br />
                                <b>Lugar: </b> {{ curso.estado }}
                                <br />
                                <b>Fecha de inicio: </b> {{ curso.fecha_inicio|date:"DATE_FORMAT" }}
                                <br />
                                <b>Fecha de culminación: </b> {{ curso.fecha_fin|date:"DATE_FORMAT" }}
                                <br />
                                <b>Duración: </b> {{ curso.horas }} horas
                                <br /><br >
                            {% endfor %}

                            <br />

                            <h4>Certificaciones</h4>
                            <hr>
                            {% for certificacion in usuario.get_profile.persona.certificacion_set.get_queryset %}
                                <b>Titulo: </b> {{ certificacion.titulo }}
                                <br />
                                <b>Código de certificación: </b> {{ certificacion.codigo }}
                                <br />
                                <b>Institución: </b> {{ certificacion.institucion }} horas
                                <br /><br >
                                <b>Fecha de inicio: </b> {{ certificacion.fecha_inicio|date:"DATE_FORMAT" }}
                                <br />
                                <b>Fecha de culminación: </b> {{ certificacion.fecha_fin|date:"DATE_FORMAT" }}
                                <br />
                                <b>Lugar: </b> {{ certificacion.pais }}
                                <br /><br />
                            {% endfor %}

                            <br />

                            <h4>Conocimientos profesionales</h4>
                            <hr>
                            {% for habilidad in usuario.get_profile.habilidad_set.get_queryset %}
                                <b>Habilidad: </b> {{ habilidad.habilidad }}
                                <br /><br />
                            {% endfor %}

                            <br />

                            <h4>Otros conocimientos</h4>
                            <hr>
                            {% for conocimiento in usuario.get_profile.conocimiento_set.get_queryset %}
                                <b>Conocimiento: </b> {{ conocimiento.otros_conocimientos }}
                                <br /><br />
                            {% endfor %}

                            <br />

                            <h4>Idiomas</h4>
                            <hr>
                            <table class="ink-table">
                                <tr>
                                    <b>
                                        <th>
                                            Idioma
                                        </th>
                                        <th>
                                            Lectura
                                        </th>
                                        <th>
                                            Escritura
                                        </th>
                                        <th>
                                            Fluidez de conversación
                                        </th>
                                    </b>
                                </tr>
                            {% for idioma in usuario.get_profile.persona.idioma_set.get_queryset %}
                                <tr align=center>
                                    <td>
                                        {{ idioma.idioma }}
                                    </td>
                                    <td>
                                        {{ idioma.get_nivel_leido_display }}
                                    </td>
                                    <td>
                                        {{ idioma.get_nivel_escrito_display }}
                                    </td>
                                    <td>
                                        {{ idioma.get_nivel_hablado_display }}
                                    </td>
                                    <td>
                                </tr>
                            {% endfor %}
                            </table>
                        </div>


                        <div id="requisitos" class="tabs-content"> 
                            {% if not usuario.get_profile.persona.auditor_set.get_queryset.exists %}
                                <h4>Registro</h4>

                                {{ usuario.get_profile.persona.primer_nombre }} {{ usuario.get_profile.persona.primer_apellido }} aún no está registrado como auditor.
                                <br /><br />

                                Puntaje:
                                {% if usuario.get_profile.competencia_set.get_query_set.exists %}
                                    {{ usuario.id|puntaje_entrevistado }}
                                {% else %}
                                    <a href="{% url 'competencia' usuario.id %}">Cargar entrevista</a>
                                {% endif %}

                                <br /><br />

                                Puntaje:
                                {% if usuario.get_profile.evaluacion_set.get_query_set.last.puntaje %}
                                    {{ usuario.get_profile.evaluacion_set.get_query_set.last.puntaje }}
                                {% else %}
                                    <a href="{% url 'evaluacion' 1 usuario.id %}">Cargar evaluación</a>
                                {% endif %}

                            {% else %}

                                {% for momento in usuario.get_profile.persona.auditor_set.get_queryset|dictsort:"fecha" %}
                                    <h4>{{ momento.estatus }}</h4>
                                    Nombre y apellido: {{ usuario.get_profile.persona.primer_nombre }} {{ usuario.get_profile.persona.segundo_nombre }}
                                    Fecha: {{ momento.fecha|date:"DATE_FORMAT" }}
                                    Estatus: {{ momento.estatus }}
                                    <hr>
                                    <br />
                                {% endfor %}
                            {% endif %}

                            <br /><br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %} 

  </body>
</html>
{% endblock %}

main/templates/perfil/editar_formulario.html
{% include "base_ink.html" %}
{% block personales %}

<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
  <body>

{% load static %}
{% load humanize %} 
 
  <!-- Main Page Content and Sidebar -->
  
<div class="ink-grid">
    {% include 'menu_perfil.html' %}
    <div class="ink-grid">
        <nav class="ink-navigation">
            <ul class="breadcrumbs">
                <li><a href="/">Inicio</a></li>
                <li><a href="{% url 'perfil' %}">Perfil</a></li>
                <li><a href="{% url 'perfil' %}#{{ titulo }}">{{ titulo|title }}</a></li>
                {% if nueva %}
                    <li class="active"><a href="#">Nueva</a></li>
                {% else %}
                    <li class="active"><a href="#">Editar</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <div class="space">
        <div class="column-group">
            <div class="space">
                <div class="space">
                    <div class="box">
                        {% if mensaje %}
                            <div class="ink-alert basic {{ tipo_mensaje }}">
                                <button class="ink-dismiss">&times;</button>
                                <p>{{ mensaje }}</p>
                            </div>
                        {% endif %}
                        <form class="ink-form" method="POST" onsubmit="return Ink.UI.FormValidator_1.validate(this);">{% csrf_token %}
                            {{ formulario.management_form }}
                            <fieldset class="column-group">
                                {% ifequal titulo 'educacion' %}
                                    <div class="ink-alert basic info">
                                        <button class="ink-dismiss">&times;</button>
                                        <p>Recuerde proporcionar información de estudios únicamente culminados</p>
                                    </div>
                                {% endifequal %}
                                {% ifequal titulo 'competencias' %}
                                {% load perfil %}
                                <h3>Indique su nivel de conocimiento en:</h3>
                                    {% for l_competencia in lista_competencia %}
                                        <table class="ink-table">
                                            <div>
                                                <tr>
                                                    <td>
                                                        <label>{{ l_competencia }}</label>
                                                    </td>
                                                    <td class="content-right">
                                                        <label for="id_nivel">Nivel:</label><br/>
                                                        {% if nueva %}
                                                          <select id="id_nivel" name="nivel">
                                                              <option value="nada_{{ l_competencia.id }}" selected="selected">Nada</option>
                                                              <option value="basico_{{ l_competencia.id }}">Básico</option>
                                                              <option value="medio_{{ l_competencia.id }}">Medio</option>
                                                              <option value="alto_{{ l_competencia.id }}">Alto</option>
                                                              <option value="experto_{{ l_competencia.id }}">Experto</option>
                                                          </select>
                                                        {% else %}
                                                              <select id="id_nivel" name="nivel">{{ l_competencia.id|nivel_elegido:persona }} 
                                                        {% endif %}
                                                        </div>
                                                    </td>
                                                </td>
                                            </div>
                                        </table>
                                    {% endfor %}
                                {% else %}
                                    {% for form in formulario %}
                                        <div class="control-group required validation">
                                            <div class="control">

                                            {% if form.errors %}
                                                <div class="ink-alert basic error">
                                                    <button class="ink-dismiss">&times;</button>
                                                        <p>{{ form.errors }}</p>
                                                </div>
                                            {% endif %}
                                            {% if form.field.required %}<span color="red">*</span>{% endif %}
                                                {{ form.label }}
                                                {% for field in form %}
                                                    {{ field.label_tag }}
                                                    {{ field  }}
                                                {% endfor %}
                                            </div>
                                            <p class="tip">{{ form.help_text }}</p>
                                        </div>
                                        <hr>
                                    {% endfor %}
                                {% endifequal %}
                            </fieldset>
                            <div>
                                <input type="submit" value="Guardar" class="ink-button blue">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %} 

  </body>
</html>
{% endblock %}